/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface Users {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  login: string;
  password_hash: string;
  role: Generated<UserRole>;
  updated_at: Generated<Timestamp>;
}

export interface Vocabularies {
  attempts: Generated<number>;
  collocations: string | null;
  correct: Generated<number>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  level: string | null;
  meaning: string;
  part_of_speech: string | null;
  pronunciation: string | null;
  reviewed_at: Timestamp | null;
  sentences: string | null;
  /**
   * 0 = new (never drilled), 1 = learning, 2 = known (memorized)
   */
  status: Generated<number>;
  streak: Generated<number>;
  updated_at: Generated<Timestamp>;
  user_id: string;
  word: string;
}

export interface DB {
  users: Users;
  vocabularies: Vocabularies;
}
